# coding=utf-8
#Procedimiento que imprime la ayuda de el juego
def Help():
    print('\n*---------------------------*')
    print('** HELP DEL JUEGO CONNECT4 **')
    print('*---------------------------*\n')
    print('> Si su opcion es el MODO PLAYER vs PLAYER lo que tiene que hacer es ingresar los nombres de ambos jugadores (el juego se los va pedir uno por uno) luego tiene que ingresar el tamaño del tablero.')
    print('> Si su opcion es el MODO PLAYER vs MACHINE lo que tiene que hacer es ingresar su nombre (cuando el juego se lo pida) luego tiene que ingresar el tamaño del tablero.')
    print('> Si su opcion es el MODO MACHINE vs MACHINE lo unico que tiene que hacer es ingresar el tamaño del tablero.')
    print('\nATENCION!!!')
    print('-> El jugador que le toca la ficha "O" es el que inicia.')
    print('-> El tamaño del tablero tiene una medida minima de 5X6 y maxima de 10X10 de lo contrario el juego le va dar ERROR.')
    print('-> El juego le va indicar por su nombre a quien le toca ingresar una ficha.')
    print('-> Procure que el numero de columna que ingrese, en su turno, este en el rango de columnas del tablero de lo contrario le va dar ERROR.')
    print('-> Si una de las columnas esta llena, ingrese la ficha en otra columna de lo contrario le va dar ERROR.')
    print('-> Si aun tiene dudas de como son las instrucciones del juego ingrese la opcion (1) INSTRUCCIONES .')
    print("***********************************************************************************************************")
    print("             Kevin Manfredy Axpuac Juárez, 15006597 , IME")
    print("             Miguel Angel Lemus Moráles, 14003328 , ITR")
    print("             Ciencias de la Computación I, Universidad Galileo, 2020")
    print('*--------------------------------------------------------------------------------------------------------*\n')